version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    versioning-strategy: "increase-if-necessary" # Allows upgrades to fix security issues but avoids breaking changes
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"] # ignore major version bumps that would require refactors, we want dependabot to be small changes and safe to one-click merge
    commit-message:
      prefix: "chore(deps)"
    groups:
      # Group for security updates
      security-patches:
        patterns:
          - "*"
        applies-to: "security-updates"

      # Group for optional version updates
      ignore-me-optional-upgrades:
        patterns:
          - "*"
        applies-to: "version-updates"
